name: Build Release
on:
  push:
    branches: [savepass_mobile]

permissions:
  contents: write

jobs:
  build-app:
    if: contains(github.event.head_commit.message, 'release')
    runs-on: [ubuntu-latest]
    steps:
      - name: Check out
        uses: actions/checkout@v1
        with:
          ref: savepass_mobile

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      - name: Setup env
        run: npm ci && npx expo prebuild

      - name: Get version
        run: echo "APP_VERSION=v$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Build
        run: cd android/ && chmod +x ./gradlew && ./gradlew assembleRelease

      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.APP_VERSION }}
          files: ./android/app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
